set echo on;

alter session set nls_language = english;
alter session set nls_date_format = 'DD-MON-YYYY';
alter session set nls_date_language = english;


INSERT INTO PASSAGIER VALUES (1, 'Collins', 'Phil', 'GB ','Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (2, 'Sting', null, 'GB ','Frankfurt', '01-01-1920', 1);                                               
INSERT INTO PASSAGIER VALUES (3, 'Bush', 'Kate', 'GB ','Frankfurt', '01-01-1920', 1);                                            
INSERT INTO PASSAGIER VALUES (4, 'Jagger', 'Mick', 'GB ','Frankfurt', '01-01-1920', 1);                                          
INSERT INTO PASSAGIER VALUES (5, 'Richards', 'Keith', 'GB ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (6, 'Gabriel', 'Peter', 'GB ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (7, 'Kaas', 'Patricia', 'F  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (8, 'Lennox', 'Annie', 'GB ','Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (9, 'Nannini', 'Gianna', 'I  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (10, 'Meatloaf', null, 'USA','Frankfurt', '01-01-1920', 1);                                           
INSERT INTO PASSAGIER VALUES (11, 'Mercury', 'Freddie', 'GB ','Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (12, 'Niedeggen', 'Wolfgang', 'D  ','Frankfurt', '01-01-1920', 1);                                  
INSERT INTO PASSAGIER VALUES (13, 'Turner', 'Tina', 'USA','Frankfurt', '01-01-1920', 1);                                         

INSERT INTO PASSAGIER VALUES (14, 'John', 'Elton', null,'Frankfurt', '01-01-1920', 1);                                             
INSERT INTO PASSAGIER VALUES (15, 'Ramazotti', 'Eros', 'I  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (16, 'Horn', 'Guildo', 'D  ','Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (17, 'Miosga', 'Sarah', null,'Frankfurt', '01-01-1920', 1);                                           
INSERT INTO PASSAGIER VALUES (18, 'Miosga', 'Pascal', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (19, 'Maiwald', 'Kai', null,'Frankfurt', '01-01-1920', 1);                                            
INSERT INTO PASSAGIER VALUES (20, 'Maiwald ', 'Rudi', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (21, 'Burhenne', 'Matthias', 'D  ','Frankfurt', '01-01-1920', 1);                                   
INSERT INTO PASSAGIER VALUES (22, 'Militz', 'Lukas', 'D  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (23, 'Hohmeyer', 'Melanie', null,'Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (24, 'Hohmeyer', 'Holger', 'D  ','Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (25, 'Bayer', 'Daniel', null,'Frankfurt', '01-01-1920', 1);                                           
INSERT INTO PASSAGIER VALUES (26, 'Bayer', 'Eberhard', 'D  ','Frankfurt', '01-01-1920', 1);                                      

INSERT INTO PASSAGIER VALUES (27, 'Hennecke', 'Christian', null,'Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (28, 'Hennecke', 'Markus', 'D  ','Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (29, 'Gueclue', 'Ilkem', null,'Frankfurt', '01-01-1920', 1);                                          
INSERT INTO PASSAGIER VALUES (30, 'Gueclue', 'Erdem', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (31, 'Tepel', 'Andreas', null,'Frankfurt', '01-01-1920', 1);                                          
INSERT INTO PASSAGIER VALUES (32, 'Tepel', 'Martin', 'D  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (35, 'Mueller', 'Tatjana', null,'Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (36, 'Mueller', 'Susi', null,'Frankfurt', '01-01-1920', 1);                                           
INSERT INTO PASSAGIER VALUES (37, 'Reinel', 'Mario', 'D  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (38, 'Reinel', 'Martin', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (39, 'Lamps', 'Bob', null,'Frankfurt', '01-01-1920', 1);                                              
INSERT INTO PASSAGIER VALUES (40, 'Lamps', 'Tom', 'D  ','Frankfurt', '01-01-1920', 1);                                           
INSERT INTO PASSAGIER VALUES (41, 'Bostanci', 'Hueseyin', 'D  ','Frankfurt', '01-01-1920', 1);                                   

INSERT INTO PASSAGIER VALUES (42, 'Bostanci', 'Sinan', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (43, 'Hahn', 'Rene', null,'Frankfurt', '01-01-1920', 1);                                              
INSERT INTO PASSAGIER VALUES (44, 'Hahn', 'Donald', 'D  ','Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (45, 'Bailleu', 'Pascal', null,'Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (47, 'Hahn', 'Andre', null,'Frankfurt', '01-01-1920', 1);                                             
INSERT INTO PASSAGIER VALUES (48, 'Hahn', 'Thomas', null,'Frankfurt', '01-01-1920', 1);                                            
INSERT INTO PASSAGIER VALUES (49, 'Scholz', 'Juergen', null,'Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (50, 'Scholz', 'Gerhard', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (51, 'Harasty', 'Sascha', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (52, 'Harasty', 'Simon', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (53, 'Schmitt', 'Stefan', null,'Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (55, 'Schmitt', 'Franz', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (56, 'Mahr', 'Florian', 'D  ','Frankfurt', '01-01-1920', 1);                                        

INSERT INTO PASSAGIER VALUES (57, 'Paulheim', 'Annika', 'D  ','Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (58, 'Klomann', 'Marcel', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (59, 'Saseno', 'Widya', 'ID ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (60, 'Ruppel', 'Florian', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (61, 'Knabe', 'Nico', 'D  ','Frankfurt', '01-01-1920', 1);                                          
INSERT INTO PASSAGIER VALUES (62, 'Lied', 'Christian', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (63, 'Hesse', 'Sebastian', 'D  ','Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (64, 'Meuer', 'Bjoern', 'D  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (65, 'Stock', 'Jan', 'D  ','Frankfurt', '01-01-1920', 1);                                           
INSERT INTO PASSAGIER VALUES (66, 'Tobert', 'Stefan', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (67, 'Kouada', 'Hichem', 'TUN','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (68, 'Englert', 'Michael', 'D  ','Frankfurt', '01-01-1920', 1);                                     
INSERT INTO PASSAGIER VALUES (69, 'Ksaier', 'Nejib', 'TUN','Frankfurt', '01-01-1920', 1);                                        

INSERT INTO PASSAGIER VALUES (70, 'Helmke', 'Christian', 'D  ','Frankfurt', '01-01-1920', 1);                                    
INSERT INTO PASSAGIER VALUES (71, 'Gannouni', 'Walid', 'TUN','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (72, 'Sanama', 'Gaspard', 'CMR','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (73, 'Fessi', 'Aymen', 'TUN','Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (74, 'Pei', 'Tao', 'CHN','Frankfurt', '01-01-1920', 1);                                             
INSERT INTO PASSAGIER VALUES (75, 'Dehler', 'Tatjana', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (76, 'Sprenger', 'Sebastian', 'D  ','Frankfurt', '01-01-1920', 1);                                  
INSERT INTO PASSAGIER VALUES (77, 'Heinz', 'Patrik', 'D  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (78, 'Haas', 'Bastian', 'D  ','Frankfurt', '01-01-1920', 1);                                        
INSERT INTO PASSAGIER VALUES (79, 'Hahn', 'Benedikt', 'D  ','Frankfurt', '01-01-1920', 1);                                       
INSERT INTO PASSAGIER VALUES (80, 'Wald', 'Daniel', 'D  ','Frankfurt', '01-01-1920', 1);                                         
INSERT INTO PASSAGIER VALUES (81, 'Schaefer', 'Thilo', 'D  ','Frankfurt', '01-01-1920', 1);                                      
INSERT INTO PASSAGIER VALUES (82, 'Nguentcheng', 'Alexandre', 'CMR','Frankfurt', '01-01-1920', 1);                               

commit;
  
